version: '3.8'

services:
  site1:
    build: ./containers/site1
    container_name: site1
    volumes:
      - /home/ad_zabbix63/DevOps_Project/containers/site1:/usr/local/apache2/htdocs
    networks:
      - my_lb_site_network
    expose:
      - 80

  site2:
    build: ./containers/site2
    container_name: site2
    volumes:
      - /home/ad_zabbix63/DevOps_Project/containers/site2:/usr/local/apache2/htdocs
    networks:
      - my_lb_site_network
    expose:
      - 80

  site3:
    build: ./containers/site3
    container_name: site3
    volumes:
      - /home/ad_zabbix63/DevOps_Project/containers/site3:/usr/local/apache2/htdocs
    networks:
      - my_lb_site_network
    expose:
      - 80

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./sample_nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_lb_site_network

networks:
  my_lb_site_network:
    driver: bridge