pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                ansiblePlaybook playbook: '/var/lib/jenkins/workspace/my_lb_site/ansible/install_dependencies.yml'
            }
        }

        stage('Prepare Directories') {
            steps {
                ansiblePlaybook playbook: '/var/lib/jenkins/workspace/my_lb_site/ansible/prepare_directories.yml'
            }
        }

        stage('Copy Files') {
            steps {
                ansiblePlaybook playbook: '/var/lib/jenkins/workspace/my_lb_site/ansible/copy_files.yml'
            }
        }

        stage('Generate HTML') {
            steps {
                ansiblePlaybook playbook: '/var/lib/jenkins/workspace/my_lb_site/ansible/generate_html.yml'
            }
        }

        stage('Deploy Containers') {
            steps {
                ansiblePlaybook playbook: '/var/lib/jenkins/workspace/my_lb_site/ansible/deploy_containers.yml'
            }
        }

        stage('Verify Setup') {
            steps {
                sh 'curl -I http://test.mzkhan.pro'
            }
        }
    }
}