pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG = '/var/lib/jenkins/.ansible/ansible.cfg'
    }

    stages {
        stage('Install Dependencies') {
            steps {
                withEnv(["ANSIBLE_CONFIG=$ANSIBLE_CONFIG"]) {
                    ansiblePlaybook playbook: '/var/lib/jenkins/workspace/my_lb_site/ansible/install_dependencies.yml'
                }
            }
        }

        stage('Prepare Directories') {
            steps {
                withEnv(["ANSIBLE_CONFIG=$ANSIBLE_CONFIG"]) {
                    ansiblePlaybook playbook: '/var/lib/jenkins/workspace/my_lb_site/ansible/prepare_directories.yml'
                }
            }
        }

        stage('Copy Files') {
            steps {
                withEnv(["ANSIBLE_CONFIG=$ANSIBLE_CONFIG"]) {
                    ansiblePlaybook playbook: '/var/lib/jenkins/workspace/my_lb_site/ansible/copy_files.yml'
                }
            }
        }

        stage('Generate HTML') {
            steps {
                withEnv(["ANSIBLE_CONFIG=$ANSIBLE_CONFIG"]) {
                    ansiblePlaybook playbook: '/var/lib/jenkins/workspace/my_lb_site/ansible/generate_html.yml'
                }
            }
        }

        stage('Deploy Containers') {
            steps {
                withEnv(["ANSIBLE_CONFIG=$ANSIBLE_CONFIG"]) {
                    ansiblePlaybook playbook: '/var/lib/jenkins/workspace/my_lb_site/ansible/deploy_containers.yml'
                }
            }
        }

        stage('Verify Setup') {
            steps {
                sh 'curl -I http://test.mzkhan.pro'
            }
        }
    }
}